<BoxLayout>:
    orientation:'vertical'
    Label:
        text: "Mext Equvalent GPA Calculator"
        font_size: 64
        color: 0.92, 0.45, 0
    Label:
        text: "Enter no. of Courses"
        font_size: 24
    Label:
        text: "Choose what you want to provide:\n\t1) Grades\n\t2) Number"
        font_size: 24
    Button:
        text: "Calculate"
        font_size: 32
        size: 20, 10